### PR TITLE
Migration to Github Actions

### PR DESCRIPTION
**Pull request by kawaijoe**

### CODE REVIEW

**Comment by kawaijoe** [comment]
I think the name is a nice touch. It's essentially the documentation for the workflow and I feel it's a good practice. In addition, I don't think the inner workings need to be shown as not everyone might understand the commands.

As for ubuntu-latest, I believe it is good practice to use the newest Ubuntu LTS.

Will change the name in a bit!

**Comment by Pante** [comment]
I think it’s kinda redundant in some parts like for flutter analyse
20.04 is the latest Ubuntu LTS

**Comment by kawaijoe** [comment]
Whoops that’s my bad. However, as suggested on the github action documentation:

> Note: The Ubuntu 20.04 virtual environment is currently provided as a preview only.

I don’t see the point of pushing for the latest version of Ubuntu when it isn’t required. I think we should leave it to github to automatically update the Ubuntu version.

https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners

**Comment by kawaijoe** [comment]
> I think it’s kinda redundant in some parts like for flutter analyse
> 20.04 is the latest Ubuntu LTS

Don’t you think it look better though 😟

**Comment by Pante** [comment]
Ehhh just use 20.04, it’s been out for quite awhile now, idk why it’s still in preview.
Also not really lol, it’s just noise

**Comment by kawaijoe** [comment]
Doesn't matter if it been out for a while, the fact is that it is still in preview for GitHub actions. Think of it as using the development branch instead of stable. Why not just wait for Ubuntu 20 to be released, especially when we don't need any of the new features.

Noise is exactly what I'm trying to remove through the names. I personally think commands should be encapsulated for the user while official actions on the other hand do not. Official actions are generally more common and hence should be left as it is to avoid confusion. Commands/unofficial actions tend to be less well known and verbose, which is why I've decided to stick to naming those.

In addition, as mentioned before, I believe it's a good practice to 'document' workflow files. I don't mind having a verbose workflow file and have a more readable GitHub actions page. After all, we'll rarely work on the workflow files.

**Comment by Pante** [comment]
I think the comparison between dev branches and this feature preview is unfair. Ubuntu 20.04 has been production ready for months by now, I don’t think it’s really considered “developmental”, nevertheless I think it’s a small issue and we can stick to Ubuntu-latest.

I disagree with keeping all the names for steps. In most cases, it’s pretty evident and self documenting, like for “flutter analyse” and “flutter test”, it’s literally described in the command itself. I feel that we should keep names only for external actions such as the flutter action and dart analyser action.

**Pull request merged**
